/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicInscriptionRouteImport } from './routes/api/public/inscription'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInscriptionRoute = ApiPublicInscriptionRouteImport.update({
  id: '/api/public/inscription',
  path: '/api/public/inscription',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/inscription': typeof ApiPublicInscriptionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/inscription': typeof ApiPublicInscriptionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/inscription': typeof ApiPublicInscriptionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/inscription'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/inscription'
  id: '__root__' | '/' | '/api/public/inscription'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicInscriptionRoute: typeof ApiPublicInscriptionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inscription': {
      id: '/api/public/inscription'
      path: '/api/public/inscription'
      fullPath: '/api/public/inscription'
      preLoaderRoute: typeof ApiPublicInscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicInscriptionRoute: ApiPublicInscriptionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
